const toursMx = {
    id: 10,
    slug: "mexico",
    nombreTour: "Juan Tours",
    operador: "Juan",
    tipoDeTour: "Tour por la playa",
    descripcion: "Podras conocer unas playas hermosas que se encuentran en Mexico",
    img: 'alguna img',
    pais: "Mexico",
    zonaLlegada: "Yucatan",
    zonaSalida: "Ciudad de Mexico",
    escalas: ['ciudad de Mexico', 'Yucatan'],
    acomodacionIncluida: true,
    transporteIncluido: true,
    edadMinima: 18,
    requisitos: {
            seguroDeViaje: true
        },
    duracionTour: 30,
    opiniones: null,
    calificacion: null,
    precioUSD: 650,
    fechasDisponibles: Object,
    - "2019": Array, Objects,        
        - id: String,
        - fechaInicio: String,
        - fechaFin: String,
        - asientosDisponibles: Number,
        - asientosReservados: Number,
        - precioRealUSD: Number,
}